# Values for fiware/keyrock Helm Chart
#
# Chart values file:
# ref: https://github.com/FIWARE/helm-charts/blob/main/charts/keyrock/values.yaml
#

## Set either an ingress or openshift route for making Keyrock externally available
##
## openshift specific route definition. Will not work on plain k8s
route:
  ## -- should the deployment create openshift routes
  enabled: false   
## ingress configuration
ingress:
  ## should there be an ingress to connect keyrock with the public internet
  enabled: false

## database configuration for keyrock
db:
  ## host of the database to be used (K8s internal service hostname)
  host: mysql.marketplace.svc.cluster.local
  ## user for connecting the database
  user: root
  ## password for connecting the database (MySQL root password)
  password: mysql-root-password

## admin configuration for accessing keyrock
admin:
  ## username of the initial keyrock admin
  user: admin
  ## password of the initial admin
  password: keyrock-admin-password
  ## email address of the admin user
  email: my@mail.org
